version: 2
jobs:
  hello_world:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: 
          name: echo Hello World
          command: |
            echo "A first hello"     
